[issue/48] - Adjust `pre-commit` hook
to print Makefile output if unsuccessful

  - refers to #33

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -7,13 +7,28 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 #echo "If the code is not working, the commit is aborted, so that you can fix it first."
 #read -p "Press Enter to continue" </dev/tty
 
-# Lint client side if flutter is installed
+# Check client side if flutter is installed
 if [ -f "$(which flutter)" ]; then
-  echo "Lint soTired app!"
-  cd "${SCRIPT_DIR}"/../ || exit 1;
-  make fluttercheck;
+  echo "Check soTired app!"
+  cd "${SCRIPT_DIR}"/../ || exit 1
+  PRE_COMMIT_RESULT="$(make fluttercheck)"
+
+  # Print if check was unsuccessful
+  if [ $? != 0 ]; then
+    echo "Failed Makefile output:"
+    cat "$PRE_COMMIT_RESULT"
+  fi
 fi
+
+# Check server side if go is installed
 if [ -f "$(which go)" ]; then
-  cd "${SCRIPT_DIR}"/../ || exit 1;
-  make gocheck;
+  echo "Check soTired server!"
+  cd "${SCRIPT_DIR}"/../ || exit 1
+  PRE_COMMIT_RESULT="$(make gocheck)"
+
+  # Print if check was unsuccessful
+  if [ $? != 0 ]; then
+    echo "Failed Makefile output:"
+    cat "$PRE_COMMIT_RESULT"
+  fi
 fi
